### ISSUE TITLE
The Data.gov team would like to coordinate

### ISSUE THREAD

**Issue by JJediny** [USSBA/sba-gov-ckan#21]
We heard of your presentation to the code.gov partners, if you can email datagovhelp@gsa.gov for introductions it would be great to setup a meeting with us and the other US federal agencies already using CKAN. Thanks in advance

**Comment by rchillard-gov** [comment]
John, it was great to meet you and chat!  I'm going to close this issue unless you think further follow up is necessary.  Glad to see so many good folks doing strong work towards more open data :)
